Repository ENG4000-Team-A/capstone-project, pull requests merged in 2021-11, with the labels that each got.

#31 Add timestamp model
  project/ConsoleTracker/ConsoleTrackerApp/admin.py
  project/ConsoleTracker/ConsoleTrackerApp/migrations/0001_initial.py
  project/ConsoleTracker/ConsoleTrackerApp/models.py
Labels: enhancement, Medium, Level 1

#32 Init socket scripts
  project/scripts/ExternalClientSocket.py
  project/scripts/InternalClientSocket.py
  project/scripts/ServerSocket.py
Labels: Low, Level 1

#44 Refactored ServerSocket, added config.json for ServerSocket
  project/scripts/ServerSocket.py
  project/scripts/config.json
Labels: enhancement

#45 Simulate User Authentication through Internal/External Client
  project/scripts/ExternalClientSocket.py
  project/scripts/InternalClientSocket.py
  project/scripts/ServerSocket.py
Labels: Low, Level 1

#48 Update requirements.txt
  project/requirements.txt
Labels: Low

#56 Add machine model
  project/ConsoleTracker/ConsoleTrackerApp/admin.py
  project/ConsoleTracker/ConsoleTrackerApp/migrations/0002_machine.py
  project/ConsoleTracker/ConsoleTrackerApp/models.py
Labels: Medium, Level 1

#46 Switch Script
  project/scripts/SwitchScript.py
Labels: Medium, Level 1

#58 connected login to socket
  project/ConsoleTracker/ConsoleTrackerApp/InternalSocketConnect.py
  project/ConsoleTracker/ConsoleTrackerApp/forms.py
  project/ConsoleTracker/ConsoleTrackerApp/templates/login.html
  project/ConsoleTracker/ConsoleTrackerApp/views.py
Labels: Medium, Level 1
