Repository ENG4000-Team-A/capstone-project, pull requests merged in 2022-02, with the labels that each got.

#126 Integrated MachineCard, updated Machine model, added Machine view
  project/ConsoleTracker/ConsoleTracker/settings.py
  project/ConsoleTracker/ConsoleTracker/urls.py
  project/ConsoleTracker/ConsoleTrackerApp/migrations/0007_machine_machine_type.py
  project/ConsoleTracker/ConsoleTrackerApp/models.py
  project/ConsoleTracker/ConsoleTrackerApp/views.py
  project/frontend/package-lock.json
  project/frontend/package.json
  project/frontend/src/App.js
  project/frontend/src/components/MachineCard.js
  project/frontend/src/components/Overview.css
  project/frontend/src/components/Overview.js
  project/requirements.txt
Labels: enhancement, Level 2

#127 Added get user api, updated top menu, working login
  project/ConsoleTracker/ConsoleTracker/urls.py
  project/ConsoleTracker/ConsoleTrackerApp/migrations/0008_alter_machine_name.py
  project/ConsoleTracker/ConsoleTrackerApp/views.py
  project/frontend/package-lock.json
  project/frontend/src/App.js
  project/frontend/src/components/Home.js
  project/frontend/src/components/Login.js
  project/frontend/src/components/Overview.js
  project/frontend/src/components/TopMenu.js
Labels: enhancement, Level 2

#147 Added Profile Page Content to home page
  project/frontend/src/components/Home.css
  project/frontend/src/components/Home.js
  project/frontend/src/components/rows.css
Labels: enhancement

#153 Readme patch
  README.md
  git
Labels: documentation

#156 CSS Mobile
  package-lock.json
  project/frontend/src/components/MachineCard.css
  project/frontend/src/components/MachineCard.js
  project/frontend/src/components/Overview.css
  project/frontend/src/components/Timer.css
  project/frontend/src/components/TopMenu.js
Labels: enhancement

#155 Add form tests
  project/ConsoleTracker/ConsoleTrackerApp/tests/test_forms.py
Labels: enhancement

#144 Machine info updated with API calls
  .gitignore
  project/frontend/src/components/MachineInfo.js
Labels: enhancement

#159 front end qr code generation
  .gitignore
  project/frontend/package-lock.json
  project/frontend/package.json
  project/frontend/src/App.js
  project/frontend/src/components/Login.js
  project/frontend/src/components/MachineInfo.js
  project/frontend/src/components/QRCodes.js
Labels: enhancement

#145 Update external db time
  project/ConsoleTracker/ConsoleTrackerApp/InternalSocketConnect.py
  project/ConsoleTracker/ConsoleTrackerApp/scripts/ExternalClientSocket.py
  project/ConsoleTracker/ConsoleTrackerApp/tasks.py
Labels: enhancement
