Repository ENG4000-Team-A/capstone-project, pull requests merged in 2022-01, with the labels that each got.

#97 Render Json Response and Dummy Response
  project/ConsoleTracker/ConsoleTrackerApp/InternalSocketConnect.py
  project/ConsoleTracker/ConsoleTrackerApp/scripts/ExternalClientSocket.py
  project/ConsoleTracker/ConsoleTrackerApp/scripts/InternalClientSocket.py
  project/ConsoleTracker/ConsoleTrackerApp/templates/ConsoleTrackerApp/Filler.html
  project/ConsoleTracker/ConsoleTrackerApp/templates/login.html
  project/ConsoleTracker/ConsoleTrackerApp/views.py
Labels: enhancement

#115 Update model upon login and improve model spec
  project/ConsoleTracker/ConsoleTrackerApp/migrations/0006_auto_20220121_1946.py
  project/ConsoleTracker/ConsoleTrackerApp/models.py
  project/ConsoleTracker/ConsoleTrackerApp/scripts/ExternalClientSocket.py
  project/ConsoleTracker/ConsoleTrackerApp/tests/test_models.py
  project/ConsoleTracker/ConsoleTrackerApp/views.py
Labels: enhancement, Medium, Level 1

#116 Smart switches updated to match Model state periodically
  project/ConsoleTracker/ConsoleTrackerApp/tasks.py
  project/ConsoleTracker/ConsoleTrackerApp/views.py
Labels: enhancement, Level 2
