Repository ENG4000-Team-A/capstone-project, pull requests merged in 2022-03, with the labels that each got.

#172 Listener and Update Time Value Upon Request
  project/ConsoleTracker/ConsoleTracker/urls.py
  project/ConsoleTracker/ConsoleTrackerApp/InternalSocketListener.py
  project/ConsoleTracker/ConsoleTrackerApp/dummyRequest.py
  project/ConsoleTracker/ConsoleTrackerApp/tasks.py
Labels: enhancement

#186 Added Instructions for SSL and Socket Listener
  README.md
Labels: documentation

#187 Updated socket to allow communication both ways
  project/ConsoleTracker/ConsoleTrackerApp/InternalSocketConnect.py
  project/ConsoleTracker/ConsoleTrackerApp/InternalSocketListener.py
  project/ConsoleTracker/ConsoleTrackerApp/dummyRequest.py
  project/ConsoleTracker/ConsoleTrackerApp/scripts/ExternalClientSocket.py
  project/ConsoleTracker/ConsoleTrackerApp/scripts/ServerSocket.py
  project/ConsoleTracker/ConsoleTrackerApp/scripts/dummyRequestToExternal.py
Labels: enhancement, Level 3

#209 Revamp nav bar
  project/frontend/src/components/TopMenu.js
Labels: enhancement

#210 Added Linux Deployment Configs
  project/ConsoleTracker/ConsoleTracker/settings.py
  project/pi_configs/README.md
  project/pi_configs/pi-book.yml
  project/pi_configs/roles/pi_setup/files/nginx-exporter.service
  project/pi_configs/roles/pi_setup/files/nginx_conf
  project/pi_configs/roles/pi_setup/files/requirements.txt
  project/pi_configs/roles/pi_setup/tasks/main.yml
  project/pi_configs/roles/pi_setup/templates/ConsoleTracker.service
Labels: enhancement

#218 Added authToken feature to views, updated react to send authToken in api
  project/ConsoleTracker/ConsoleTracker/urls.py
  project/ConsoleTracker/ConsoleTrackerApp/auth.py
  project/ConsoleTracker/ConsoleTrackerApp/views.py
  project/frontend/package-lock.json
  project/frontend/src/App.js
  project/frontend/src/components/Home.js
  project/frontend/src/components/Login.js
  project/frontend/src/components/MachineInfo.js
  project/frontend/src/components/Timer.js
  project/frontend/src/components/TopMenu.js
  project/requirements.txt
Labels: enhancement, Level 2

#248 added ssl for frontend deploy. updated nginx configs
  project/ConsoleTracker/ConsoleTracker/settings.py
  project/pi_configs/roles/pi_setup/files/CTcerts/myAwesomeCA.cer
  project/pi_configs/roles/pi_setup/files/CTcerts/myAwesomeCA.cnf
  project/pi_configs/roles/pi_setup/files/CTcerts/myAwesomeCA.pvk
  project/pi_configs/roles/pi_setup/files/CTcerts/myAwesomeServer.cer
  project/pi_configs/roles/pi_setup/files/CTcerts/myAwesomeServer.ext
  project/pi_configs/roles/pi_setup/files/CTcerts/myAwesomeServer.pvk
  project/pi_configs/roles/pi_setup/files/CTcerts/myAwesomeServer.req
  project/pi_configs/roles/pi_setup/files/nginx_conf
  project/pi_configs/roles/pi_setup/tasks/main.yml
  project/pi_configs/roles/pi_setup/templates/ExternalClientSocket.service
  project/pi_configs/roles/pi_setup/templates/ServerSocket.service
Labels: enhancement
